DPCWeb/Areas/admin/Controllers/AdminProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DPCWeb.Models;

namespace DPCWeb.Areas.admin.Controllers
{
    public class AdminProjectController : Controller
    {
        private dpcpEntities db = new dpcpEntities();

        // GET: admin/AdminProject
        public ActionResult Index()
        {
            var tbl_Project = db.Tbl_Project.Include(t => t.Tbl_Menus);
            return View(tbl_Project.ToList());
        }

        // GET: admin/AdminProject/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Project tbl_Project = db.Tbl_Project.Find(id);
            if (tbl_Project == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Project);
        }

        // GET: admin/AdminProject/Create
        public ActionResult Create()
        {
            ViewBag.menu_Id = new SelectList(db.Tbl_Menus, "menu_Id", "menu_Name");
            return View();
        }

        // POST: admin/AdminProject/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Project_Id,menu_Id,Project_Name,Project_Type,Project_Status,Priority")] Tbl_Project tbl_Project)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Project.Add(tbl_Project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.menu_Id = new SelectList(db.Tbl_Menus, "menu_Id", "menu_Name", tbl_Project.menu_Id);
            return View(tbl_Project);
        }

        // GET: admin/AdminProject/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Project tbl_Project = db.Tbl_Project.Find(id);
            if (tbl_Project == null)
            {
                return HttpNotFound();
            }
            ViewBag.menu_Id = new SelectList(db.Tbl_Menus, "menu_Id", "menu_Name", tbl_Project.menu_Id);
            return View(tbl_Project);
        }

        // POST: admin/AdminProject/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Project_Id,menu_Id,Project_Name,Project_Type,Project_Status,Priority")] Tbl_Project tbl_Project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.menu_Id = new SelectList(db.Tbl_Menus, "menu_Id", "menu_Name", tbl_Project.menu_Id);
            return View(tbl_Project);
        }

        // GET: admin/AdminProject/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int proimgcnt = db.Tbl_Project_Img.Where(s => s.Project_Id == id).Count();
            if (proimgcnt > 0)
            {
                ViewBag.ermsg = "You should delete all the images related to project then try to delete a project..";
                //return RedirectToAction("Delete", id);
            }

            Tbl_Project tbl_Project = db.Tbl_Project.Find(id);
            if (tbl_Project == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Project);
        }

        // POST: admin/AdminProject/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            int proimgcnt = db.Tbl_Project_Img.Where(s => s.Project_Id == id).Count();
            if (proimgcnt > 0)
            {
                ViewBag.ermsg = "You should delete all the images related to project then try to delete a project..";
                return RedirectToAction("Delete", id);
               
            }
            else
            {
                Tbl_Project tbl_Project = db.Tbl_Project.Find(id);
                db.Tbl_Project.Remove(tbl_Project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DPCWeb/Areas/admin/Views/AdminProject/Create.cshtml
@model DPCWeb.Models.Tbl_Project

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm("Create", "AdminProject", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()


    <div class="forms">
        <div class="row">
            <h3 class="title1">Add Project :</h3>
            <div class="form-three widget-shadow">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Menu</label>
                        <div class="col-md-8">
                            @Html.DropDownList("menu_Id", null, htmlAttributes: new { @class = "form-control1" })
                            @Html.ValidationMessageFor(model => model.menu_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Project Name</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Project_Name, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Project_Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Project Type</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Project_Type, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Project_Type, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Project Status</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Project_Status, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Project_Status, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Priority</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Submit</button> </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

DPCWeb/Areas/admin/Views/AdminProject/Delete.cshtml
@model DPCWeb.Models.Tbl_Project

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div class="forms">
    <div class="row">
        <h3 class="title1">Delete :</h3>
        <div class="form-three widget-shadow">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Project_Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Project_Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Project_Type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Project_Type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Project_Status)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Project_Status)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Priority)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Priority)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tbl_Menus.menu_Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tbl_Menus.menu_Name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()


    <div class="form-group">
        <div class="col-md-offset-1">
            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Delete</button>
               | @Html.ActionLink("Back to List", "Index") </div>
            <span class="danger">@ViewBag.ermsg</span>
        </div>
    </div>
    @*<div class="form-group no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink("Back to List", "Index")
    </div>*@
            }
        </div>
        </div>
    </div>

DPCWeb/Areas/admin/Views/AdminProject/Details.cshtml
@model DPCWeb.Models.Tbl_Project

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="forms">
    <div class="row">
        <h3 class="title1">Details :</h3>
        <div class="form-three widget-shadow">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Project_Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Project_Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Project_Type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Project_Type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Project_Status)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Project_Status)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Priority)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Priority)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tbl_Menus.menu_Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tbl_Menus.menu_Name)
                </dd>

            </dl>
        </div>
        </div>
    </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Project_Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

DPCWeb/Areas/admin/Views/AdminProject/Edit.cshtml
@model DPCWeb.Models.Tbl_Project

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="forms">
        <div class="row">
            <h3 class="title1">Edit Project :</h3>
            <div class="form-three widget-shadow">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Project_Id)

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Menu</label>
                        <div class="col-md-8">
                            @Html.DropDownList("menu_Id", null, htmlAttributes: new { @class = "form-control1" })
                            @Html.ValidationMessageFor(model => model.menu_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Project Name</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Project_Name, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Project_Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Project Type</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Project_Type, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Project_Type, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Project Status</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Project_Status, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Project_Status, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Priority</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Save</button> </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

DPCWeb/Areas/admin/Views/AdminProject/Index.cshtml
@model IEnumerable<DPCWeb.Models.Tbl_Project>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

                      <div class="tables">
                          <h2 class="title1">Projects:</h2>
                          <div class="panel-body widget-shadow">



                              <div class="row">
                                  <div class="col-sm-12 col-md-6">
                                      <div class="dataTables_length" id="example2_length">
                                          <a href="@Url.Action("Create")" class="btn btn-info btn-flat btn-pri"><i class="fa fa-plus" aria-hidden="true" style="height: 38px;"></i>Add Project</a>
                                      </div>
                                  </div>
                              </div>
                              <table id="example2" class="table table-bordered table-hover display nowrap" style="width:100%">
                                  <thead>
                                      <tr>
                                          <th>
                                              Project Name
                                          </th>
                                          <th>
                                              Project Type
                                          </th>
                                          <th>
                                              Project Status
                                          </th>
                                          <th>
                                              Priority
                                          </th>
                                          <th>
                                              Menu
                                          </th>
                                          <th></th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      @foreach (var item in Model)
                                      {
                                          <tr>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Project_Name)
                                              </td>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Project_Type)
                                              </td>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Project_Status)
                                              </td>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Priority)
                                              </td>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Tbl_Menus.menu_Name)
                                              </td>
                                              <td>

                                                  <a href="@Url.Action("Edit", new { id = item.Project_Id })"><i class="glyphicon glyphicon-edit"></i></a>

                                                  <a href="@Url.Action("Details", new { id = item.Project_Id })"><i class="glyphicon glyphicon-list-alt"></i></a>

                                                  <a href="@Url.Action("Delete", new { id = item.Project_Id })"><i class="glyphicon glyphicon-trash"></i></a>


                                          </tr>
                                      }
                                  </tbody>

                              </table>
                          </div>

                      </div>                       