DPCWeb/Areas/admin/Controllers/ProjectImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DPCWeb.Models;
using System.Text.RegularExpressions;
using DPCWeb.services;

namespace DPCWeb.Areas.admin.Controllers
{
    public class ProjectImageController : Controller
    {
        private dpcpEntities db = new dpcpEntities();

        EntityImage entityimg;
        ServiceImage serviceimg;
        // GET: admin/ProjectImage
        public ActionResult Index()
        {
            var tbl_Project_Img = db.Tbl_Project_Img.Include(t => t.Tbl_Project);
            return View(tbl_Project_Img.ToList());
        }

        // GET: admin/ProjectImage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Project_Img tbl_Project_Img = db.Tbl_Project_Img.Find(id);
            if (tbl_Project_Img == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Project_Img);
        }

        // GET: admin/ProjectImage/Create
        public ActionResult Create()
        {
            ViewBag.Project_Id = new SelectList(db.Tbl_Project, "Project_Id", "Project_Name");
            return View();
        }

        // POST: admin/ProjectImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tbl_Project_Img obj, HttpPostedFileBase[] imgfile)
        {
            try
            {
                // TODO: Add insert logic here
                var menu = (from n in db.Tbl_Menus join p in db.Tbl_Project on n.menu_Id equals p.menu_Id where p.Project_Id == obj.Project_Id select n.menu_Name).FirstOrDefault();
                
                Tbl_Project_Img te = new Tbl_Project_Img();

                foreach (var item in imgfile)
                {
                    
                    if (item != null)
                    {

                        entityimg = new EntityImage();
                        serviceimg = new ServiceImage();

                        entityimg.Imgsrc = item;
                        entityimg.Width = 800;
                        entityimg.Height = 533;
                        
                     
                        if (serviceimg.CheckImgDimension(entityimg))
                        {
                      
                            if (menu == "Architecture")
                            {
                                entityimg.SavePath = "/Content/images/Architecture/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }
                            else if (menu == "Compitition")
                            {
                                entityimg.SavePath = "/Content/images/Compitition/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }
                            else if (menu == "Urban")
                            {
                                entityimg.SavePath = "/Content/images/Urban/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }
                            else if (menu == "Town Planning")
                            {
                                entityimg.SavePath = "/Content/images/TownPlanning/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }

                            te.Project_Id = obj.Project_Id;
                            db.Tbl_Project_Img.Add(te);
                            db.SaveChanges(); 

                        }
                        else
                        {
                            ViewBag.imgerror = "Image Dimension should be 800*533 Pixel";
                            ViewBag.Project_Id = new SelectList(db.Tbl_Project, "Project_Id", "Project_Name");
                            return View();
                        }
                    }
                    
                }
                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.Project_Id = new SelectList(db.Tbl_Project, "Project_Id", "Project_Name");
                return View();
            }
        }

        // GET: admin/ProjectImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Project_Img tbl_Project_Img = db.Tbl_Project_Img.Find(id);
            if (tbl_Project_Img == null)
            {
                return HttpNotFound();
            }
            ViewBag.Project_Id = new SelectList(db.Tbl_Project, "Project_Id", "Project_Name", tbl_Project_Img.Project_Id);
            return View(tbl_Project_Img);
        }

        // POST: admin/ProjectImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tbl_Project_Img obj, FormCollection fc, HttpPostedFileBase imgfile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // TODO: Add update logic here

                    var menu = (from n in db.Tbl_Menus join p in db.Tbl_Project on n.menu_Id equals p.menu_Id where p.Project_Id == obj.Project_Id select n.menu_Name).FirstOrDefault();

                    var te = db.Tbl_Project_Img.Find(obj.Project_Img_Id);
                    te.Project_Id = obj.Project_Id;

                    if (imgfile != null)
                    {
                        entityimg = new EntityImage();
                        serviceimg = new ServiceImage();

                        entityimg.Imgsrc = imgfile;
                        entityimg.Width = 800;
                        entityimg.Height = 533;


                        if (serviceimg.CheckImgDimension(entityimg))
                        {
                            //delete img file---------------------------------------------------
                            serviceimg = new ServiceImage();
                            serviceimg.DeleteProjectImage(obj);
                            //----------------------------------------------------------------------------------
                            if (menu == "Architecture")
                            {
                                entityimg.SavePath = "/Content/images/Architecture/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }
                            else if (menu == "Compitition")
                            {
                                entityimg.SavePath = "/Content/images/Compitition/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }
                            else if (menu == "Urban")
                            {
                                entityimg.SavePath = "/Content/images/Urban/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }
                            else if (menu == "Town Planning")
                            {
                                entityimg.SavePath = "/Content/images/TownPlanning/";
                                te.Project_Imgsrc = serviceimg.AddProjectImages(entityimg);
                            }

                            te.Project_Id = obj.Project_Id;
                            

                        }
                        else
                        {
                
                            ViewBag.imgerror = "Image Dimension should be 800*533 Pixel";
                            ViewBag.Project_Id = new SelectList(db.Tbl_Project, "Project_Id", "Project_Name", obj.Project_Id);
                            return View(obj);
                        }

                    }
                    else
                    {
                        string strpath = fc["profile"];
                        te.Project_Imgsrc = strpath;

                    }
                    db.SaveChanges();

                    
                }
                catch
                {
                    return View();
                }
            }
            ViewBag.Project_Id = new SelectList(db.Tbl_Project, "Project_Id", "Project_Name", obj.Project_Id);
            return RedirectToAction("Index");
        }

        // GET: admin/ProjectImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Project_Img tbl_Project_Img = db.Tbl_Project_Img.Find(id);
            if (tbl_Project_Img == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Project_Img);
        }

        // POST: admin/ProjectImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //delete img file---------------------------------------------------
            string deldbpath = db.Tbl_Project_Img.Where(x => x.Project_Img_Id == id).Select(s => s.Project_Imgsrc).FirstOrDefault();

DPCWeb/Areas/admin/Views/ProjectImage/Create.cshtml
@model DPCWeb.Models.Tbl_Project_Img

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("Create", "ProjectImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="forms">
        <div class="row">
            <h3 class="title1">Add Project Images :</h3>
            <div class="form-three widget-shadow">
                <div class="form-horizontal">
                    
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Project_Id, "Project_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-sm-8">
                            @Html.DropDownList("Project_Id", null, htmlAttributes: new { @class = "form-control1" })
                            @Html.ValidationMessageFor(model => model.Project_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Project_Imgsrc, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            <input type="file" id="file" multiple="" name="imgfile" onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])"> <p class="help-block">Image Dimension should be 800*533 Pixel</p>
                            <img id="blah" alt="image" width="100" />
                        </div>
                        <div class="col-sm-2">
                            <p class="help-block" style="color:red">@ViewBag.imgerror</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Add</button> </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

<script type="text/javascript">
    var _URL = window.URL || window.webkitURL;
    $("#file").change(function (e) {
        var file, img;
        if ((file = this.files[0])) {
            img = new Image();
            img.onload = function () {
                if (this.width != 800 && this.height != 533) {
                    swal("Uploaded Image Dimension = " + this.width + " x " + this.height + " is not Allowed \n It should be 800 x 533");
                }

            };
            img.src = _URL.createObjectURL(file);
        }
    });
</script>

DPCWeb/Areas/admin/Views/ProjectImage/Delete.cshtml
@model DPCWeb.Models.Tbl_Project_Img

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<h3>Are you sure you want to delete this?</h3>
<div class="forms">
    <div class="row">
        <h3 class="title1">Delete Project Image :</h3>
        <div class="form-three widget-shadow">
            <dl class="dl-horizontal">
                <dt>
                    Project Image
                </dt>

                <dd>
                    <img src="@Model.Project_Imgsrc" width="100" height="100" alt="image" />
                </dd>

                <dt>
                   Project Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tbl_Project.Project_Name)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-offset-1">
            <div class="col-sm-offset">
                <button type="submit" class="btn btn-default">Delete</button>
                | @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>

            
            }
        </div>
        </div>
    </div>

DPCWeb/Areas/admin/Views/ProjectImage/Details.cshtml
@model DPCWeb.Models.Tbl_Project_Img

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="forms">
    <div class="row">
        <h3 class="title1">Details :</h3>
        <div class="form-three widget-shadow">
            <dl class="dl-horizontal">
                <dt>
                    Project Image
                </dt>

                <dd>
                    <img src="@Model.Project_Imgsrc" width="100" height="100" alt="image" />
                </dd>

                <dt>
                   Project Name
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tbl_Project.Project_Name)
                </dd>

            </dl>
        </div>
        </div>
    </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Project_Img_Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

DPCWeb/Areas/admin/Views/ProjectImage/Edit.cshtml
@model DPCWeb.Models.Tbl_Project_Img

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("Edit", "ProjectImage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="forms">
        <div class="row">
            <h3 class="title1">Edit Project Images :</h3>
            <div class="form-three widget-shadow">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Project_Img_Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Project_Id, "Project_Id", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.DropDownList("Project_Id", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Project_Id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Project_Imgsrc, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            <input type="file" id="fileid" name="imgfile" onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])" /><p class="help-block">Image Dimension should be 800*533 Pixel</p>
                            <input type="hidden" value="@Model.Project_Imgsrc" name="profile" />
                            <img src="@Model.Project_Imgsrc" id="blah" alt="img" width="100" height="100" />
                        </div>
                        <div class="col-md-2">
                            <p class="help-block" style="color:red">@ViewBag.imgerror</p>
                        </div>

                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Save</button> </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

<script type="text/javascript">
    var _URL = window.URL || window.webkitURL;
    $("#fileid").change(function (e) {
        var file, img;
        if ((file = this.files[0])) {
            img = new Image();
            img.onload = function () {
                if (this.width != 800 && this.height != 533) {
                    swal("Uploaded Image Dimension = " + this.width + " x " + this.height + " is not Allowed \n It should be 800 x 533");
                }

            };
            img.src = _URL.createObjectURL(file);
        }
    });
</script>

DPCWeb/Areas/admin/Views/ProjectImage/Index.cshtml
@model IEnumerable<DPCWeb.Models.Tbl_Project_Img>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

                      <div class="tables">
                          <h2 class="title1">Project Images</h2>
                          <div class="panel-body widget-shadow">



                              <div class="row">
                                  <div class="col-sm-12 col-md-6">
                                      <div class="dataTables_length" id="example2_length">
                                          <a href="@Url.Action("Create")" class="btn btn-info btn-flat btn-pri"><i class="fa fa-plus" aria-hidden="true" style="height: 38px;"></i>Add New</a>
                                      </div>
                                  </div>
                              </div>
                              <table id="example2" class="table table-bordered table-hover display nowrap" style="width:100%">
                                  <thead>
                                      <tr>
                                          <th>
                                              Project Image
                                          </th>
                                          <th>
                                              Project Name
                                          </th>
                                          <th>
                                              Menu
                                          </th>
                                          <th></th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      @foreach (var item in Model)
                                      {
                                          <tr>
                                              <td>
                                                  <img src="@item.Project_Imgsrc" width="45" height="45" />
                                              </td>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Tbl_Project.Project_Name)
                                              </td>
                                              <td>
                                                  @Html.DisplayFor(modelItem => item.Tbl_Project.Tbl_Menus.menu_Name)
                                              </td>
                                              <td>

                                                  <a href="@Url.Action("Edit", new { id = item.Project_Img_Id })"><i class="glyphicon glyphicon-edit"></i></a>

                                                  <a href="@Url.Action("Details", new { id = item.Project_Img_Id })"><i class="glyphicon glyphicon-list-alt"></i></a>

                                                  <a href="@Url.Action("Delete", new { id = item.Project_Img_Id })"><i class="glyphicon glyphicon-trash"></i></a>

                                              </td>
                                          </tr>


                                      }
                                  </tbody>

                              </table>
                          </div>

                      </div>

                    