DPCWeb/Controllers/AboutController.cs
using DPCWeb.Models;
using DPCWeb.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DPCWeb.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/
        IAward objrepo;

       
        public AboutController()
        {
            objrepo = new RepoAward(new dpcpEntities());
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Careers()
        {
            return View();
        }

        public ActionResult Award()
        {
            var award = objrepo.get_All_AwardImg();
            return View(award);
        }
    }
}

DPCWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DPCWeb.Models;
using DPCWeb.Repository;

namespace DPCWeb.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
       IHome objrepo;

        EntityHome objEntity;
        public HomeController()
        {
            objrepo = new RepoHome(new dpcpEntities());
        }
        public ActionResult Index()
        {
            objEntity = new EntityHome();

            objEntity.Banner = objrepo.getallBanner();
            objEntity.Services = objrepo.getallServices();
            return View(objEntity);
        }

    }
}

DPCWeb/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DPCWeb.Repository;
using DPCWeb.Models;

namespace DPCWeb.Controllers
{
    public class TeamController : Controller
    {
        //
        // GET: /Team/
         IEmployee Iobj;
         dpcpEntities dc = new dpcpEntities();

        public TeamController()
         {
             Iobj = new RepoEmployee(new dpcpEntities());
         }

        public ActionResult Index()
         {
             ViewBag.deptNo = dc.Sp_GetDeptCount().ToList();
             var p = dc.Sp_GetDeptCount().Select(x => x.dept_id).ToList();
             var Emp = Iobj.get_All_Employee().ToList();
             return View(Emp);
            
        }

    }
}

DPCWeb/Views/Home/Index.cshtml
@model DPCWeb.Models.EntityHome
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutIndex.cshtml";
}

@*<h2>Index</h2>*@

@*<style>
    .dropdown-submenu {
        position: relative;
    }

        .dropdown-submenu .dropdown-menu {
            top: 0;
            left: 100%;
            margin-top: -1px;
        }

        span.intro::first-letter {
    color: #ff0000;
    font-size:200%;
        }  
</style>*@
<!-- banner -->
<div id="home" class="w3ls-banner">
    <!-- header -->
    <div class="header-w3l">
        <div class="header-main">
            <div class="header-top-agileits">
                <div class="container">
                    <nav class="navbar navbar-default">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <h1 data-aos="fade-down">
                                <a href="#"><img src="~/Temp/images/logo200.png" class="imglogo"></a>
                            </h1>
                        </div>
                        <!-- navbar-header -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                            <ul class="nav navbar-nav navbar-right" data-aos="fade-up">
                                <li><a class="active" href="#"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                                <li class="dropdown menu__item">
                                    <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" data-hover="Pages" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> About<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Profile", "Index", "About")</li>
                                        <li>@Html.ActionLink("Our Team", "Index", "Team")</li>
                                        <li>@Html.ActionLink("Careers", "Careers", "About")</li>
                                        <li>@Html.ActionLink("Award & Publication", "Award", "About")</li>
                                    </ul>
                                </li>
                                <li class="dropdown menu__item">
                                    <a href="#" class="dropdown-toggle menu__link" data-toggle="dropdown" data-hover="Pages" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-picture-o" aria-hidden="true"></i> Projects<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Architecture", "Architecture", "Project")</li>
                                        <li>@Html.ActionLink("Urban Design", "UrbanDesign", "Project")</li>
                                        <li>@Html.ActionLink("Town Planning", "TownPlanning", "Project")</li>
                                        <li>@Html.ActionLink("Compitition", "Compitition", "Project")</li>
                                    </ul>
                                </li>
                                <li><a href="@Url.Action("Index","Contact")"><i class="fa fa-phone" aria-hidden="true"></i> Contact</a></li>

                            </ul>

                        </div>
                        <div class="clearfix"> </div>
                    </nav>
                </div>
            </div>
            
        </div>
        <div class="clearfix"> </div>
        <!-- //Nav -->
    </div>
    <!-- //header -->
    <!-- banner-text -->
    <div class="slider">
        <div class="callbacks_container">
            <ul class="rslides callbacks callbacks1" id="slider4">
                @foreach (var item in Model.Banner)
                {
                    <li>
                        <div class="w3layouts-banner-top" style="background-image: url('@item.ImgSrc');">

                            @*<div class="agileits-banner-info">
                                    <h3>Welcome To <span>Design Point Consult</span></h3>
                                </div>*@

                        </div>
                    </li>
                }
                
              
            </ul>
        </div>
        <div class="clearfix"> </div>

        <!--//banner text-->
    </div>
   
</div>
<!-- //banner -->
<!-- //banner -->
<!-- Modal2 -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>

                <div class="signin-form profile">
                    <h3 class="agileinfo_sign">Login</h3>
                    <div class="login-form">
                        <form action="#" method="post">
                            <input type="email" name="email" placeholder="E-mail" required="">
                            <input type="password" name="password" placeholder="Password" required="">
                            <div class="tp">
                                <input type="submit" value="Login">
                            </div>
                        </form>
                    </div>
                    <div class="login-social-grids">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        </ul>
                    </div>
                    <p><a href="#" data-toggle="modal" data-target="#myModal3"> Don't have an account?</a></p>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- banner-bottom -->
<div class="about">
    <div class="agileits_w3layouts_heding">
        <p>What we do</p>
        <h3><span>About</span> Us</h3>
        <img src="~/Temp/images/head1.png" alt="Lines" />
    </div>
    <div class="banner_bottom_right">
    </div>
    <div class="col-md-7 banner_bottom_left">
        <h3>We Provide Professional Services</h3>
        <p class="para-w3layouts white">
                Our firm has its beginnings in the year 1993 as Design Point. It was subsequently restructured as Design
            Point Vision India Consult to accommodate all its various work spheres within similar setup. Originally founded as a 
            consulting firm in the field of Architecture and Town Planning; DPC Pvt. Ltd. has grown to become a multidisciplinary 
            design team due to its commitment to client service and quality design. Currently we are going through the process of 
            cons olidation and are truly poised towards International networking.
            <br/>
                To provide complete basic infrastructure to encourage economic growth through strategic development of roads to
            promote social upliftment and improvement of quality of life experienced by the people of Jaisingpur Identification 
            of projects aimed at triggering urban development.
        </p>
        <div class="wthree_more wthree_more1">
            @Html.ActionLink("Read More...", "Index", "About")
        </div>
    </div>
    <div class="clearfix"> </div>
</div>
<!-- //banner-bottom -->
<!-- /services -->
<div class="agile_services">
    <div class="container">
        <div class="agileits_w3layouts_heding">
            <p>We provide best Solutions</p>
            <h3>Our <span>Services</span></h3>
            <img src="~/Temp/images/head1.png" alt="Lines" />
        </div>
        <div class="markets-grids">
            @foreach (var item in Model.Services)
            {
                <div class="col-md-4 w3ls-markets-grid">
                    <div class="agileits-icon-grid">
                        <div class="icon-left">
                            <i class="@item.fa_fa_class" aria-hidden="true"></i>
                        </div>
                        <div class="icon-right">
                            <h5>@item.service</h5>

                        </div>
                        <div class="clearfix"> </div>

                    </div>
                </div>
            }
           
          
         
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //services -->
<!-- Modal1 -->
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <div class="agileits_w3layouts_heding">
                    <h3>Pla <span>Fond</span></h3>
                    <img src="~/Temp/images/head1.png" alt="Lines" />
                </div>
                <div class="col-md-6 img-modal-w3l"><img src="images/g1.jpg" alt=" " class="img-responsive"></div>
                <div class="col-md-6 modal-info">
                    <h5>Roof installation</h5>
                    <p>Mauris sollicitudin scelerisque commodo.Nunc dapibus mauris sed metus.</p>
                    <h5>Roof repair</h5>
                    <p>Mauris sollicitudin scelerisque commodo.Nunc dapibus mauris sed metus.</p>
                </div>
                <div class="clearfix"> </div>
                <div class="col-md-6 modal-info text-right">
                    <h5>Roof leak repair</h5>
                    <p>Mauris sollicitudin scelerisque commodo.Nunc dapibus mauris sed metus.</p>
                    <h5>Emergency roof repair</h5>
                    <p>Mauris sollicitudin scelerisque commodo.Nunc dapibus mauris sed metus.</p>
                </div>
                <div class="col-md-6 img-modal-w3l"><img src="images/g8.jpg" alt=" " class="img-responsive"></div>
                <div class="clearfix"> </div>
                <div class="col-md-6 img-modal-w3l"><img src="images/g9.jpg" alt=" " class="img-responsive"></div>
                <div class="col-md-6 modal-info">
                    <h5>Roof management</h5>
                    <p>Mauris sollicitudin scelerisque commodo.Nunc dapibus mauris sed metus.</p>
                    <h5>Roof coating</h5>
                    <p>Mauris sollicitudin scelerisque commodo.Nunc dapibus mauris sed metus.</p>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
<!-- //Modal1 -->
<!-- schedule-bottom -->

<!-- //schedule-bottom -->
<!-- features -->

<!-- //features -->
<!-- portfolio -->

<!-- //portfolio -->

<!-- contact -->