DPCWeb/Areas/admin/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DPCWeb.Models;
using DPCWeb.services;

namespace DPCWeb.Areas.admin.Controllers
{
    public class BannerController : Controller
    {
        private dpcpEntities db = new dpcpEntities();

        EntityImage entityimg;
        ServiceImage serviceimg;
        // GET: admin/Banner
        public ActionResult Index()
        {
            return View(db.Tbl_Banner.ToList());
        }

        // GET: admin/Banner/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Banner tbl_Banner = db.Tbl_Banner.Find(id);
            if (tbl_Banner == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Banner);
        }

        // GET: admin/Banner/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/Banner/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Discription,ImgSrc,Priority")] Tbl_Banner obj, HttpPostedFileBase imgfile)
        {
            if (ModelState.IsValid)
            {
                Tbl_Banner te = new Tbl_Banner();
               
                if (imgfile != null)
                {
                    entityimg = new EntityImage();
                    entityimg.Imgsrc = imgfile;
                    entityimg.Width = 1680;
                    entityimg.Height = 900;

                    serviceimg = new ServiceImage();
                    if (serviceimg.CheckImgDimension(entityimg))
                    {

                        entityimg.SavePath = "/Content/images/Banner/";
                        te.ImgSrc = serviceimg.AddImages(entityimg);

                        te.Name = obj.Name;
                        te.Priority = obj.Priority;
                        te.Discription = obj.Discription;

                        db.Tbl_Banner.Add(te);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        @ViewBag.imgerror = "Image Dimension should be 1680*900 Pixel";

                    }


                }
                
                
            }
            return View(obj);
            
        }

        // GET: admin/Banner/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Banner tbl_Banner = db.Tbl_Banner.Find(id);
            if (tbl_Banner == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Banner);
        }

        // POST: admin/Banner/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tbl_Banner obj, HttpPostedFileBase imgfile,FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var te = db.Tbl_Banner.Find(obj.Id);
                te.Name = obj.Name;
                te.Discription = obj.Discription;
                te.Priority = obj.Priority;

                if (imgfile != null)
                {
                    entityimg = new EntityImage();
                    entityimg.Imgsrc = imgfile;
                    entityimg.Width = 1680;
                    entityimg.Height = 900;

                    serviceimg = new ServiceImage();
                    if (serviceimg.CheckImgDimension(entityimg))
                    {

                        entityimg.SavePath = "/Content/images/Banner/";
                        te.ImgSrc = serviceimg.AddImages(entityimg);

                        db.Entry(te).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                     
                    }
                }
                else
                {
                    string strpath = fc["profile"];
                    te.ImgSrc = strpath;

                    db.Entry(te).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

                
            }
            ViewBag.imgerror = "Image Dimension should be 1680*900 Pixel";
            return View(obj);
        }

        // GET: admin/Banner/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Banner tbl_Banner = db.Tbl_Banner.Find(id);
            if (tbl_Banner == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Banner);
        }

        // POST: admin/Banner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Banner tbl_Banner = db.Tbl_Banner.Find(id);
            db.Tbl_Banner.Remove(tbl_Banner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DPCWeb/Areas/admin/Views/Banner/Create.cshtml
@model DPCWeb.Models.Tbl_Banner

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("Create", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="forms">
        <div class="row">
            <h3 class="title1">Add Banner :</h3>
            <div class="form-three widget-shadow">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Name</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Description</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Discription, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Discription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Banner Image</label>
                        <div class="col-sm-8">
                            <input type="file" id="file" required="" name="imgfile" onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])"> <p class="help-block">Image Dimension should be 1680*900 Pixel</p>
                            <img id="blah" alt="image" width="100" />
                        </div>
                        <div class="col-sm-2">
                            <p class="help-block" style="color:red">@ViewBag.imgerror</p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Priority</label>
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Submit</button> </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

<script type="text/javascript">
    var _URL = window.URL || window.webkitURL;
    $("#file").change(function (e) {
        var file, img;
        if ((file = this.files[0])) {
            img = new Image();
            img.onload = function () {
                if (this.width != 1680 && this.height != 900)
                {
                    swal("Uploaded Image Dimension = " + this.width + " x " + this.height + " is not Allowed \n It should be 1680 x 900");
                }
               
            };
            img.src = _URL.createObjectURL(file);
        }
    });
</script>

DPCWeb/Areas/admin/Views/Banner/Delete.cshtml
@model DPCWeb.Models.Tbl_Banner

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>Are you sure you want to delete this?</h3>

<div class="forms">
    <div class="row">
        <h3 class="title1">Delete :</h3>
        <div class="form-three widget-shadow">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Discription)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Discription)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ImgSrc)
                </dt>

                <dd>
                    <img src="@Model.ImgSrc" width="100" height="100" alt="image" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Priority)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Priority)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-offset-1">
            <div class="col-sm-offset">
                <button type="submit" class="btn btn-default">Delete</button>
                | @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
            }
        </div>
        </div>
        </div>

DPCWeb/Areas/admin/Views/Banner/Details.cshtml
@model DPCWeb.Models.Tbl_Banner

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="forms">
    <div class="row">
        <h3 class="title1">Details :</h3>
        <div class="form-three widget-shadow">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Discription)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Discription)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ImgSrc)
                </dt>

                <dd>
                    <img src="@Model.ImgSrc" width="100" height="100" alt="image" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Priority)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Priority)
                </dd>

            </dl>
        </div>
        </div>
    </div>
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>

DPCWeb/Areas/admin/Views/Banner/Edit.cshtml
@model DPCWeb.Models.Tbl_Banner

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Edit", "Banner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="forms">
        <div class="row">
            <h3 class="title1">Edit</h3>
            <div class="form-three widget-shadow">
                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Discription, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Discription, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Discription, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ImgSrc, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            <input type="file" id="fileid" name="imgfile" onchange="document.getElementById('blah').src = window.URL.createObjectURL(this.files[0])" /><p class="help-block">Image Dimension should be 1680*900 Pixel</p>
                            <input type="hidden" value="@Model.ImgSrc" name="profile" />
                            <img src="@Model.ImgSrc" id="blah" alt="img" width="100" height="100" />
                        </div>
                        <div class="col-md-2">
                            <p class="help-block" style="color:red">@ViewBag.imgerror</p>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control1" } })
                            @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-8">
                            <div class="col-sm-offset"> <button type="submit" class="btn btn-default">Submit</button> </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

<script type="text/javascript">
    var _URL = window.URL || window.webkitURL;
    $("#fileid").change(function (e) {
        var file, img;
        if ((file = this.files[0])) {
            img = new Image();
            img.onload = function () {
                if (this.width != 1680 && this.height != 900) {
                    swal("Uploaded Image Dimension = " + this.width + " x " + this.height + " is not Allowed \n It should be 1680 x 900");
                }

            };
            img.src = _URL.createObjectURL(file);
        }
    });
</script>

DPCWeb/Areas/admin/Views/Banner/Index.cshtml
@model IEnumerable<DPCWeb.Models.Tbl_Banner>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

                      <div class="tables">
                          <h2 class="title1">Banner</h2>
                          <div class="panel-body widget-shadow">



                              <div class="row">
                                  <div class="col-sm-12 col-md-6">
                                      <div class="dataTables_length" id="example2_length">
                                          <a href="@Url.Action("Create")" class="btn btn-info btn-flat btn-pri"><i class="fa fa-plus" aria-hidden="true" style="height: 38px;"></i>Add New</a>
                                      </div>
                                  </div>
                              </div>
                              <table id="example2" class="table table-bordered table-hover display nowrap" style="width:100%">
                                  <thead>
                                      <tr>
                                          <th>
                                              Name
                                          </th>
                                          <th>
                                              Description
                                          </th>
                                          <th>
                                             Image
                                          </th>
                                          <th>
                                             Priority
                                          </th>
                                          <th></th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      @foreach (var item in Model)
                                      {
                                        <tr>
                                            <td>
                                                @Html.HiddenFor(modelItem => item.Id)
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Discription)
                                            </td>
                                            <td>
                                               
                                                <img src="@item.ImgSrc" width="45" height="45" />
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Priority)
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Edit", new { id = item.Id })"><i class="glyphicon glyphicon-edit"></i></a>

                                                <a href="@Url.Action("Details", new { id = item.Id })"><i class="glyphicon glyphicon-list-alt"></i></a>

                                                <a href="@Url.Action("Delete", new { id = item.Id })"><i class="glyphicon glyphicon-trash"></i></a>
                                            </td>
                                        </tr>
                                      }
                                  </tbody>

                              </table>
                          </div>

                      </div>